# Week 2 

## introduces you to Python libraries and concepts used in research.

### In week 2, you will:

Learn about Python scope rules;
Learn the basics of scientific and vectorized computing using numpy;
Learn the basics of plotting with matplotlib.pyplot;
Learn the basics of random numbers with the random module;
Learn how to measure time

### 2.1.1: Scope Rules
# LEGB 
### Local
Local is the current function you're in.
### Enclosing Function
Enclosing function is the function that called the current function, if any.
### Global
Global refers to the module in which the function was defined.
### Built-in
And built-in refers to Python's built-in namespace.

In [ ]:
We first call main.
Main calls update.
The execution then returns to main.
And once main exits, we return the global scope,
the scope where we defined the functions main and update.



In [ ]:
def update(n,x):
    n = 2                    #Remember that variables that are 
    x.append(4)              #created within a function, such as n
     print('update: ', n, x) #in the case of the update function, 
                             #are deleted as soon as Python exits
                             #that function.
def main():
    n = 1
    x = [0,1,2,3]
    print('main: ', n, x)
    update(n,x)
    print('main: ', n, x)

main()

In [ ]:
Here, n and x are assigned in the function main,
so when we get to the first print function,
Python finds the objects n and x in the local scope,
meaning that the values of the objects are n equal to 1
and x is equal to 0, 1, 2, 3, a list.

The program then calls the function update with arguments
n and x.
So the program's control then moves to the function update.
All of the function update has a parameter, n.
On the first line of the function, we have an assignment,
n equals 2, which creates a new variable that happens to
be called "n," And its value is set to 2.
On the second line, we append the number 4
to the object x, which is one of the function's parameters.
Just to be clear on terminology, remember
that an argument is an object that is passed to a function
as its input when the function is called.
A parameter, in contrast, is a variable that is used
in the function definition to refer to that argument.
That means that the second line will append the number 4 to
the list that we have created in the main function.
So when we get to the print function, Python
finds the objects n and x in the local scope,
meaning that the values of the objects are n equal to 2
and x is a list, 0, 1, 2, 3, 4.

Python then exits the function and control returns to the
main function.
Remember that variables that are created within a function, 
such as n in the case of the update function, are deleted
as soon as Python exits that function.

Looking at the final print function, the objects n and x
are found in the local scope where n is equal to 1
and x is a list, 0, 1, 2, 3 4.

In [ ]:
def increment(n): 
   n += 1 
   print(n) 

n = 1 
increment(n) 
print(n) 

In [ ]:
Fill in the #blank# to ensure this prints 10.

In [ ]:
def increment(n):
   n += 1
   return n # blank #

n = 1
while n < 10:
   n = increment(n)
print(n)

### 2.1.2: Classes and Object-Oriented Programming
Aprenda lo básico de la herencia en lo que respecta a las clases y la programación orientada a objetos.

In general, an object consists of both internal data and methods
that perform operations on the data.

Inheritance means that you can define a new object type, a new class, that inherits properties from an existing object

Un objeto es una instancia de la clase: the class statement doesn't create any instance of the class

In [ ]:
# Clase derivada de list: puede redefinir cualquier attributo
# heredado de list, y además, puede agregar sus nuevos y propios attributes.

class Mylist(list): # Notice that we placed parentheses after MyList.
                    # This is how Python specifies inheritance.
# When a class is created via inheritance, the new class
# inherits the attributes defined by its base class, the 
# class it is inheriting attributes from -- in this case -- a list. 



The functions defined inside a class are known as "instance methods" because they operate on an instance of the class.

By convention, the name of the class instance is called "self",and it is always passed as the first argument
to the functions defined as part of a class.

In [1]:
class Mylist(list):
    def remove_min(self):
        self.remove(min(self))
    def remove_max(self):
        self.remove(max(self))

In [9]:
x = [1,5,7,9,4,5,7]
y = Mylist(x)
dir(y) #you'll see that the method to remove max and remove min
       #are now available

In [10]:
y.remove_min()

In [11]:
y

[5, 7, 9, 4, 5, 7]

In [12]:
y.remove_max()
y

[5, 7, 4, 5, 7]

### 2.2.1: Introduction to NumPy Arrays

NumPy is a Python module designed for scientific computation.

NumPy arrays are n-dimensional array objects

NumPy arrays are an additional data type provided by NumPy,
and they are used for representing vectors and matrices.

In [14]:
import numpy as np
zero_vector = np.zeros(5)
zero_matrix = np.zeros((5,3)) 

In [15]:
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [20]:
m = np.array([[1,3],[5,6]])
m

array([[1, 3],
       [5, 6]])

In [21]:
mt = m.transpose()
mt

array([[1, 5],
       [3, 6]])

In [22]:
np.array([0., 0., 0., 0., 0.])

array([0., 0., 0., 0., 0.])

In [26]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [28]:
x = np.array([[3,6],[5,7]]) 
y = x.transpose() 
print(y) 

[[3 5]
 [6 7]]


### 2.2.2: Slicing NumPy Arrays