# Week 2 

## introduces you to Python libraries and concepts used in research.

### In week 2, you will:

Learn about Python scope rules;
Learn the basics of scientific and vectorized computing using numpy;
Learn the basics of plotting with matplotlib.pyplot;
Learn the basics of random numbers with the random module;
Learn how to measure time

### 2.1.1: Scope Rules
# LEGB 
### Local
Local is the current function you're in.
### Enclosing Function
Enclosing function is the function that called the current function, if any.
### Global
Global refers to the module in which the function was defined.
### Built-in
And built-in refers to Python's built-in namespace.

In [ ]:
We first call main.
Main calls update.
The execution then returns to main.
And once main exits, we return the global scope,
the scope where we defined the functions main and update.



In [ ]:
def update(n,x):
    n = 2                    #Remember that variables that are 
    x.append(4)              #created within a function, such as n
     print('update: ', n, x) #in the case of the update function, 
                             #are deleted as soon as Python exits
                             #that function.
def main():
    n = 1
    x = [0,1,2,3]
    print('main: ', n, x)
    update(n,x)
    print('main: ', n, x)

main()

In [ ]:
Here, n and x are assigned in the function main,
so when we get to the first print function,
Python finds the objects n and x in the local scope,
meaning that the values of the objects are n equal to 1
and x is equal to 0, 1, 2, 3, a list.

The program then calls the function update with arguments
n and x.
So the program's control then moves to the function update.
All of the function update has a parameter, n.
On the first line of the function, we have an assignment,
n equals 2, which creates a new variable that happens to
be called "n," And its value is set to 2.
On the second line, we append the number 4
to the object x, which is one of the function's parameters.
Just to be clear on terminology, remember
that an argument is an object that is passed to a function
as its input when the function is called.
A parameter, in contrast, is a variable that is used
in the function definition to refer to that argument.
That means that the second line will append the number 4 to
the list that we have created in the main function.
So when we get to the print function, Python
finds the objects n and x in the local scope,
meaning that the values of the objects are n equal to 2
and x is a list, 0, 1, 2, 3, 4.

Python then exits the function and control returns to the
main function.
Remember that variables that are created within a function, 
such as n in the case of the update function, are deleted
as soon as Python exits that function.

Looking at the final print function, the objects n and x
are found in the local scope where n is equal to 1
and x is a list, 0, 1, 2, 3 4.

In [ ]:
def increment(n): 
   n += 1 
   print(n) 

n = 1 
increment(n) 
print(n) 

In [ ]:
Fill in the #blank# to ensure this prints 10.

In [ ]:
def increment(n):
   n += 1
   return n # blank #

n = 1
while n < 10:
   n = increment(n)
print(n)

### 2.1.2: Classes and Object-Oriented Programming
Aprenda lo básico de la herencia en lo que respecta a las clases y la programación orientada a objetos.

In general, an object consists of both internal data and methods
that perform operations on the data.

Inheritance means that you can define a new object type, a new class, that inherits properties from an existing object

Un objeto es una instancia de la clase: the class statement doesn't create any instance of the class

In [ ]:
# Clase derivada de list: puede redefinir cualquier attributo
# heredado de list, y además, puede agregar sus nuevos y propios attributes.

class Mylist(list): # Notice that we placed parentheses after MyList.
                    # This is how Python specifies inheritance.
# When a class is created via inheritance, the new class
# inherits the attributes defined by its base class, the 
# class it is inheriting attributes from -- in this case -- a list. 



The functions defined inside a class are known as "instance methods" because they operate on an instance of the class.

By convention, the name of the class instance is called "self",and it is always passed as the first argument
to the functions defined as part of a class.

In [ ]:
class Mylist(list):
    def remove_min(self):
        self.remove(min(self))
    def remove_max(self):
        self.remove(max(self))

In [ ]:
x = [1,5,7,9,4,5,7]
y = Mylist(x)
dir(y) #you'll see that the method to remove max and remove min
       #are now available

In [ ]:
y.remove_min()

In [ ]:
y

In [ ]:
y.remove_max()
y

### 2.2.1: Introduction to NumPy Arrays

NumPy is a Python module designed for scientific computation.

NumPy arrays are n-dimensional array objects

NumPy arrays are an additional data type provided by NumPy,
and they are used for representing vectors and matrices.

In [ ]:
import numpy as np
zero_vector = np.zeros(5)
zero_matrix = np.zeros((5,3)) 

In [ ]:
zero_matrix

In [ ]:
x = np.array([1,2,3])
x

In [ ]:
m = np.array([[1,3],[5,6]])
m

In [ ]:
mt = m.transpose()
mt

In [ ]:
np.array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros(5)

In [ ]:
x = np.array([[3,6],[5,7]]) 
y = x.transpose() 
print(y) 

### 2.2.2: Slicing NumPy Arrays

With two-dimensional arrays, the first index specifies the row of the array and the second index
specifies the column of the array.

With multi-dimensional arrays, you can use the colon character in place of a fixed value for an index, which
means that the array elements corresponding to all values of that particular index will be returned.

In [2]:
import numpy as np
x = np.array([1,2,3])
y = np.array([2,4,6])
X = np.array([[1,2,3],[4,5,6]])
Y = np.array([[2,4,6],[8,10,12]])

In [3]:
x

array([1, 2, 3])

In [4]:
X

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
x[2] 

3

In [6]:
x[0:2] # Slicing 

array([1, 2])

In [8]:
z = x + y  
z

array([3, 6, 9])

In [9]:
X[:,1] # Columna 1

array([2, 5])

In [10]:
X[:,0] # Columna 0

array([1, 4])

In [11]:
X[:,1] + Y[:,1]

array([ 6, 15])

In [14]:
X[0,:]   # Fila 0

array([1, 2, 3])

In [15]:
X[0]  # Fila 0

array([1, 2, 3])

In [21]:
x = np.array([1,2,5]) 
#Recall that indices start at 0 in Python.
#The end of a slice (i.e., the number to the right of the colon) is not included 
# in the slice.
x[1:2]

array([2])

### 2.2.3: Indexing NumPy Arrays

In [23]:
z1 = np.array([1,2,3,4,5,6])

In [24]:
z2 = z1 + 1
z2

array([2, 3, 4, 5, 6, 7])

In [28]:
index_list = [1,2,3]

In [29]:
z2[index_list]

array([3, 4, 5])

In [30]:
index_array = np.array(index_list)

In [31]:
z2[index_array]

array([3, 4, 5])

In [34]:
z1 > 3 # Let's first construct a Boolean array.

array([False, False, False,  True,  True,  True])

In [35]:
z1[z1  > 3]

array([4, 5, 6])

In [36]:
z2[z1 > 3] #Python returns those elements
           #of the array for which the corresponding value in the Boolean vector is true.

array([5, 6, 7])

In [37]:
index_bol = z1 > 3
z2[index_bol]

array([5, 6, 7])

When you slice an array using the colon operator, you get a view of the object.
This means that if you modify it, the original array will also be modified.
This is in contrast with what happens when you index an array, in which case
what is returned to you is a copy of the original data.

In [38]:
z1 = np.array([1,3,5,7,9])

In [40]:
w = z1[0:3] # Slicing 
w

array([1, 3, 5])

In [42]:
w[0] = 3
w

array([3, 3, 5])

In [43]:
z1

array([3, 3, 5, 7, 9])

In [44]:
z2 = np.array([1,3,5,7,9])

In [47]:
w2 = z2[[0,1,2]] # Indexing
w2

array([1, 3, 5])

In [49]:
w2[0] = 3
w2

array([3, 3, 5])

In [50]:
z2

array([1, 3, 5, 7, 9])

In [51]:
a = np.array([1,2]) 
b = np.array([3,4,5]) 
b[a]

array([4, 5])

In [60]:
c = b[1:] 
c

array([4, 5])

In [61]:
b[a] is c

False

### 2.2.4: Building and Examining NumPy Arrays

To construct an array of 10 linearly spaced elements starting with 0
and ending with 100, we can use the NumPy linspace function.

In [62]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

Now, to construct an average of 10 logarithmically spaced elements
between 10 and 100, we can do the following.
In this case we use the NumPy logspace command.
But now careful, the first argument that goes into logspace
is going to be the log of the starting point.
If you want the sequence to start at 10, the first argument
has to be the log of 10 which is 1.
The second argument is the endpoint of the array, which is 100.
And again, we need to put in the log of that, which is 2.
And the third argument as before, is the number of elements in our array.

In [63]:
np.logspace(1,2,10)

array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

In [64]:
np.logspace(np.log10(250),np.log10(500),10)

array([250.        , 270.01493472, 291.63225989, 314.98026247,
       340.19750004, 367.43362307, 396.85026299, 428.62199143,
       462.93735614, 500.        ])

In [65]:
X.shape # Cantidad de filas y columnas

(2, 3)

In [66]:
X.size # Cantidad de elementos

6

In [67]:
x = np.random.random(10)

In [68]:
x

array([0.26687465, 0.92372933, 0.34347374, 0.75459398, 0.78227022,
       0.14368719, 0.17420349, 0.82658949, 0.00437661, 0.04138033])

In [69]:
np.any( x > 0.9)

True

In [70]:
np.all(x >= 0.1)

False